using System.ComponentModel.DataAnnotations;
using WMS.DAL.Common;

namespace WMS.Web.Models.Inbound;

// Block 4.5.2 chunk d.1 — shared form VM consumed by the _PoForm
// partial. Create + Edit views project their domain VMs into this
// shape via PurchaseOrderFormProjections so the partial reads from
// a single contract.
//
// DataAnnotations duplicate PurchaseOrderCreateViewModel's attrs
// because client-side jQuery validation reads attrs generated by
// asp-for on the partial's @model (= this type). Server-side POST
// still binds to PurchaseOrderCreateViewModel / EditViewModel — those
// retain their own validators. Duplication is intentional + accepted
// for d.1; a future block may fold both domain VMs into this shape.
public sealed class PurchaseOrderFormViewModel
{
    // --- Mode + identity --------------------------------------------

    // 'create' | 'edit'. Drives partial conditionals (d.2 adds the
    // edit-specific chrome — status badge, locked field rendering,
    // audit footer). d.1: always 'create' since Edit.cshtml is not
    // yet wired through the partial.
    public string Mode { get; set; } = "create";

    // Populated on Edit only (used for breadcrumb / Detail link).
    public Guid? Id { get; set; }

    // Status enum value — null on Create. Edit projects from
    // PurchaseOrderEditViewModel.Status. d.2 renders the badge.
    public string? Status { get; set; }

    // --- Header fields (Create-editable / Edit-locked) --------------

    [Required(ErrorMessage = "PO number is required.")]
    [StringLength(50, ErrorMessage = "PO number must be at most 50 characters.")]
    [Display(Name = "PO number")]
    public string PoNumber { get; set; } = "";

    [Required(ErrorMessage = "Vendor is required.")]
    [Display(Name = "Vendor")]
    public Guid OwnerId { get; set; }

    [Required(ErrorMessage = "Warehouse is required.")]
    [Display(Name = "Warehouse")]
    public Guid WarehouseId { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Expected date")]
    public DateOnly? ExpectedDate { get; set; }

    [StringLength(1000)]
    [Display(Name = "Notes")]
    public string? Notes { get; set; }

    // --- Display-only strings for Edit-locked fields ----------------
    // Populated by the Edit projection so the partial can render
    // "WH-MAIN · Main Warehouse" style read-only values without
    // re-resolving lookups. Null on Create.
    public string? VendorCode { get; set; }
    public string? VendorName { get; set; }
    public string? WarehouseCode { get; set; }

    // --- Lines ------------------------------------------------------

    public List<PurchaseOrderLineViewModel> Lines { get; set; } = new();

    // --- Lookup data (controller-populated) -------------------------

    public IReadOnlyList<LookupItem> Vendors    { get; set; } = Array.Empty<LookupItem>();
    public IReadOnlyList<LookupItem> Warehouses { get; set; } = Array.Empty<LookupItem>();
    public IReadOnlyList<LookupItem> Products   { get; set; } = Array.Empty<LookupItem>();
    public IReadOnlyList<LookupItem> Uoms       { get; set; } = Array.Empty<LookupItem>();

    // --- Locks (computed server-side; client never elevates) --------

    public PurchaseOrderFormLocks Locks { get; set; } = new();

    // --- Audit footer (Edit only; d.5 populates) --------------------

    public PurchaseOrderFormAudit? Audit { get; set; }
}

// Server-computed boolean flags read by the partial to decide locked
// vs editable rendering. Create projection sets everything to false +
// truthy (= all editable). Edit projection sets per status + receipts.
// d.1: shape introduced; partial does not yet read these (Create
// render path is unconditional). d.2 wires the rendering branches.
public sealed class PurchaseOrderFormLocks
{
    public bool PoNumber { get; set; }
    public bool Vendor { get; set; }
    public bool Warehouse { get; set; }
    public bool ExpectedDate { get; set; }
    public bool Notes { get; set; }

    // Existing convention from PurchaseOrderEditViewModel — true when
    // any line has ReceivedQuantity > 0. Read by the existing grid
    // factory; preserved here for d.2.
    public bool LinesLocked { get; set; }

    public bool CanAddLines { get; set; } = true;
    public bool CanRemoveLines { get; set; } = true;
    public bool CanReorderLines { get; set; } = true;
}

// Created/Updated stamps for the Edit footer. d.5 populates from
// CreatedAt/CreatedBy + UpdatedAt/UpdatedBy columns on the entity
// plus IUserRepository name lookups. Null on Create.
public sealed class PurchaseOrderFormAudit
{
    public DateTime CreatedAt { get; set; }
    public string? CreatedByName { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public string? UpdatedByName { get; set; }
}
