<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WMS.BLL\WMS.BLL.csproj" />
    <ProjectReference Include="..\WMS.DAL\WMS.DAL.csproj" />
    <ProjectReference Include="..\WMS.Domain\WMS.Domain.csproj" />
    <ProjectReference Include="..\WMS.Common\WMS.Common.csproj" />
    <ProjectReference Include="..\WMS.Plugins\WMS.Plugins.csproj" />
    <ProjectReference Include="..\WMS.Jobs\WMS.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.Core3.Web.Demo" Version="2024.1.6" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.*" />
    <PackageReference Include="Telerik.UI.for.AspNet.Core" Version="2023.3.1010" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
